const enum AppErrorCode {
  AUTH_EMAIL_ALREADY_EXISTS = " AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_ROLE = "AUTH_INVALID_ROLE",
  AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  AUTH_NOT_FOUND = "AUTH_NOT_FOUND",
  AUTH_TOO_MANY_ATTEMPTS = "AUTH_TOO_MANY_ATTEMPTS",
  AUTH_UNAUTHORIZED_ACCESS = " AUTH_UNAUTHORIZED_ACCESS",
  AUTH_TOKEN_NOT_FOUND = " AUTH_TOKEN_NOT_FOUND",

  // Access Control Errors
  ACCESS_FORBIDEN = " ACCESS_FORBIDEN",
  ACCESS_UNAUTHORIZED = "ACCESS_UNAUTHORIZED",

  // Validation and Ressource Errors
  VALIDATION_ERROR = " VALIDATION_ERROR",
  RESSOURCE_NOT_FOUND = "RESSOURCE_NOT_FOUND",
  DUPLICATE_KEY  = "DUPLICATE_KEY",

  // System Errors
  INTERNAL_SERVER_ERROR = " INTERNAL_SERVER_ERROR ",
  VERIFICATION_ERROR = " VERIFICATION_ERROR",

  // Email Errors
  EMAIL_QUEUE_FAILURE = "EMAIL_QUEUE_FAILURE",
  EMAIL_STATUS_CHECK_FAILURE = "EMAIL_STATUS_CHECK_FAILURE",
  AUTH_FORBIDDEN = "AUTH_FORBIDDEN",

}

export default AppErrorCode;